# Imagem base oficial da Microsoft para devcontainers Node.js

# Versão 22 LTS — mais estável e com suporte longo

FROM mcr.microsoft.com/devcontainers/javascript-node:1-22-bookworm



# nodemon: reinicia o servidor automaticamente ao salvar arquivos

# É o equivalente ao Spring Boot DevTools que você usou no Java

RUN npm install -g nodemon



WORKDIR /workspace
